version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    
    ports:
      - 1323:1323
    
    networks: 
      - simplesim

  # frontend:
  # TODO: Add container to run front end code in developer mode

networks:
  simplesim: {}
